// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsdqsixlsxobpfjuctxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzZHFzaXhsc3hvYnBmanVjdHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjE1ODMsImV4cCI6MjA2MzkzNzU4M30.P1AB04l_QDd-GyULMZ__-0wm2RkWnYTizd6QhhZdPfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);